import {StyleSheet} from 'react-native'
import { HEADER_FONT_COLOR, LINE_COLOR, UI_ACTIVE_COLOR } from '../../../lib/color';

export default styles = StyleSheet.create({
    cardRoot:{
        borderRadius:8,
        margin:10,
        overflow:'hidden',
        paddingBottom:10
    },
    cardInfoTextWrapper:{
        flex:1,
        marginRight:50,
        marginTop:10,
        marginLeft:10
    },
    cardType:{
        color:HEADER_FONT_COLOR,
        marginBottom:5,
        fontSize:12
    },
    bankName:{
        color:HEADER_FONT_COLOR,
        marginBottom:5,
        fontSize:16
    },
    cardNumber:{
        color:HEADER_FONT_COLOR,
        fontSize:16
    },
    cardImage:{
        width:50,
        height:50,
        marginTop:10,
        marginLeft:10,
        zIndex:99,
        backgroundColor:HEADER_FONT_COLOR,
        borderRadius:25
    },
    textInput:{
        fontSize:16,
        flex:1,
        width:'100%'
    },
    inputViewRoot:{
        width:'100%',
        flexDirection:'row',
        backgroundColor:HEADER_FONT_COLOR,
        paddingVertical:20,
        borderBottomWidth:1,
        borderColor:LINE_COLOR
    },
    title:{
        paddingHorizontal:20,
        fontSize:16
    },
    selectLocationTouchable:{
        borderBottomWidth:1,
        borderColor:LINE_COLOR,
        paddingVertical:20,
        paddingHorizontal:10,
        flexDirection:'row',
        justifyContent:'space-between'
    },
    arrowText:{
        fontSize:18
    },
    submitButtonTouchable:{
        backgroundColor:UI_ACTIVE_COLOR,
        borderRadius:8,
        width:'80%',
        paddingVertical:10,
        alignSelf:'center',
        marginVertical:10
    },
    submitButtonText:{
        color:HEADER_FONT_COLOR,
        textAlign:'center'
    },
    textInputRoot:{
        marginHorizontal:10
    }
});